#ifndef Mike_ERROR_H
#define Mike_ERROR_H

enum Mike_Error {
	Mike_ERROR = 1
	, Mike_ERROR_EOTL

	, Mike_ERROR_PNG_NOT
	, Mike_ERROR_PNG_INT32

	, Mike_ERROR_PNG_IHDR_NOT
	, Mike_ERROR_PNG_IHDR_LENGTH
	, Mike_ERROR_PNG_IHDR_COLORTYPE
	, Mike_ERROR_PNG_IHDR_BITDEPTH
	, Mike_ERROR_PNG_IHDR_COMPRESSIONMETHOD
	, Mike_ERROR_PNG_IHDR_FILTERMETHOD
	, Mike_ERROR_PNG_IHDR_INTERLACEMETHOD
	, Mike_ERROR_PNG_IHDR_NONSEQUENTIAL
	, Mike_ERROR_PNG_IHDR_EXTRA

	, Mike_ERROR_PNG_PLTE_ORDER
	, Mike_ERROR_PNG_PLTE_MISSING

	, Mike_ERROR_PNG_IDAT_MISSING
	, Mike_ERROR_PNG_DEFLATE_INCOMPLETE

	, Mike_ERROR_PNG_CHUNK_UNKNOWN_CRITICAL
};

#endif
